# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibbla < Formula
  desc "Dibbla CLI for managing Dibbla applications"
  homepage "https://dibbla.com"
  version "1.2.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.10/dibbla_1.2.10_darwin_amd64.tar.gz"
      sha256 "8688e935c519a093c7dbb5e989bc4576fe79a6f9ff93ba99786761ab186f14b3"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.10/dibbla_1.2.10_darwin_arm64.tar.gz"
      sha256 "a7c3d1dbfe822c29071d4d9dd00fae44237a5b420572add3b07b7df275f28bf6"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.10/dibbla_1.2.10_linux_amd64.tar.gz"
      sha256 "96c51313edf04a3605abdcc1ec8d50863ee3c1cb40463f7d951bf6185f5663b2"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.10/dibbla_1.2.10_linux_arm64.tar.gz"
      sha256 "9bb0284dfbf8f8dd4fcb889a826db5a2dde84721cbc7c982eccb90bdd2350c94"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  test do
    system "#{bin}/dibbla --version"
  end
end
