# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibbla < Formula
  desc "Dibbla CLI for managing Dibbla applications"
  homepage "https://dibbla.com"
  version "1.1.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.1.22/dibbla_1.1.22_darwin_amd64.tar.gz"
      sha256 "789a7e6cfcdbf47943a8a350bfb9ae59207493827e9ce385bffa619048a534af"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.1.22/dibbla_1.1.22_darwin_arm64.tar.gz"
      sha256 "6435c8c5932723dcaa1a4df0d1af8cf285370f5e793cb7ea6057bcaa563b6b49"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.1.22/dibbla_1.1.22_linux_amd64.tar.gz"
      sha256 "dfd3baf5a9d348731849e475a978f2ff48ef66a46d499441f7cf37e0990af72e"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.1.22/dibbla_1.1.22_linux_arm64.tar.gz"
      sha256 "8ae1a91a05c2e1b9d7c0b514c46256dd31d5bc72fe8ecd8cb303042b04db405d"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  test do
    system "#{bin}/dibbla --version"
  end
end
