# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dibbla < Formula
  desc "Dibbla CLI for managing Dibbla applications"
  homepage "https://dibbla.com"
  version "1.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.6/dibbla_1.2.6_darwin_amd64.tar.gz"
      sha256 "900c750fa60635f243a65874cbe9c5c26c601417874767945ec16a7faf1140d8"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.6/dibbla_1.2.6_darwin_arm64.tar.gz"
      sha256 "49924e847ed4c3463ea6cbc09cb2fefc1990ef8892166d93af28908bead62a2d"

      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.6/dibbla_1.2.6_linux_amd64.tar.gz"
      sha256 "bb9a84790d85f9571dd36a798e9fd3bfb29baa9e5d55b095abc9f3b8f39cc863"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dibbla-agents/dibbla-cli/releases/download/v1.2.6/dibbla_1.2.6_linux_arm64.tar.gz"
      sha256 "ec097807ba2af2f49ee2ca5005dd8d8f43475a2a6adb5c5512c2f33d9c900ba0"
      define_method(:install) do
        bin.install "dibbla"
        # Generate and install shell completions
        (bash_completion/"dibbla").write `#{bin}/dibbla completion bash`
        (zsh_completion/"_dibbla").write `#{bin}/dibbla completion zsh`
        (fish_completion/"dibbla.fish").write `#{bin}/dibbla completion fish`
      end
    end
  end

  test do
    system "#{bin}/dibbla --version"
  end
end
